### PR TITLE
support bionic

### PR DESCRIPTION
**Pull request by mhilton**

### CODE REVIEW

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/bundleservice-charm/33/

**Review by rogpeppe — APPROVED** [review]
LGTM

**Review by jcsackett — APPROVED** [review]

**Comment by mhilton** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/bundleservice-charm-merge

**Comment by jujugui** [comment]
Build failed: Attempt to land pull request failed
        build url: http://ci-gce.jujugui.org:8080/job/bundleservice-charm-merge/22

**Pull request merged**
