### PR TITLE
Build specifically for xenial

### PR DESCRIPTION
**Pull request by makyo**

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/bundleservice-charm/30/
Test PASSed.

**Comment by bac** [comment]
:+1:

**Review by bac — APPROVED** [review]

**Review by jrwren — APPROVED** [review]
👍

**Comment by makyo** [comment]
Big green button, merge build not yet working

**Pull request merged**
