### PR TITLE
Create bundleservice-charm

### PR DESCRIPTION
**Pull request by bac**

### CODE REVIEW

**Comment by bac** [comment]
This is the initial pass at the bundleservices charm. There is no deb yet so it hasn't been exercised. No QA is possible.

One note: I did not include the logs relations in this pass as I wasn't sure if they are needed.  Can easily be added later.

**Comment by jrwren** [comment]
👍

**Comment by makyo** [comment]
👍

**Comment by bac** [comment]
:shipit:

**Comment by jujugui** [comment]
Merged build finished. Test FAILed.

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/bundleservice-charm/2/
Test FAILed.

**Comment by jujugui** [comment]
Merged build finished. Test FAILed.

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/bundleservice-charm/3/
Test FAILed.

**Comment by jujugui** [comment]
Merged build finished. Test PASSed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/bundleservice-charm/4/
Test PASSed.

**Comment by bac** [comment]
:shipit:

**Comment by bac** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/bundleservice-charm-merge

**Comment by jujugui** [comment]
Build failed: Attempt to land pull request failed
        build url: http://ci.jujugui.org:8080/job/bundleservice-charm-merge/2

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/bundleservice-charm-merge

**Comment by jujugui** [comment]
Build failed: Attempt to land pull request failed
        build url: http://ci.jujugui.org:8080/job/bundleservice-charm-merge/3

**Comment by jujugui** [comment]
Merged build finished. Test FAILed.

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/bundleservice-charm-merge/4/
Test FAILed.

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/bundleservice-charm-merge

**Comment by jujugui** [comment]
Build failed: Attempt to land pull request failed
        build url: http://ci.jujugui.org:8080/job/bundleservice-charm-merge/5

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/bundleservice-charm-merge

**Pull request merged**
